[package]
name = "tbuild"
version = "0.1.0"
edition = "2021"
license = "TCL"
description = "TontooOS app builder"
authors = ["arlomu"]

[[bin]]
name = "tbuild"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
toml = "0.8"
walkdir = "2"
zip = { version = "2", default-features = false, features = ["deflate"] }